/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as ExportRouteImport } from './routes/export'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/export': typeof ExportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/stories/$id': typeof StoriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/export': typeof ExportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/stories/$id': typeof StoriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/export': typeof ExportRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/stories/$id': typeof StoriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/collect' | '/export' | '/library' | '/settings' | '/stories/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collect' | '/export' | '/library' | '/settings' | '/stories/$id'
  id:
    | '__root__'
    | '/'
    | '/collect'
    | '/export'
    | '/library'
    | '/settings'
    | '/stories/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectRoute: typeof CollectRoute
  ExportRoute: typeof ExportRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  StoriesIdRoute: typeof StoriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectRoute: CollectRoute,
  ExportRoute: ExportRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  StoriesIdRoute: StoriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
